In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier

In [2]:
os.getcwd()

'C:\\Users\\Sagar'

In [3]:
os.chdir ('C:\\Users\\Sagar\\Downloads')
os.getcwd()

'C:\\Users\\Sagar\\Downloads'

In [4]:
df=pd.read_csv("audi.csv")
display(df)

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]

In [5]:
len(df)

10668

In [6]:
display (df.shape)

(10668, 9)

In [7]:
display (df.dtypes )

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [8]:
display (df.isna().sum() )

model           0
year            0
price           0
transmission    0
mileage         0
fuelType        0
tax             0
mpg             0
engineSize      0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB


In [10]:
df.describe ()

year          price        mileage           tax           mpg  \
count  10668.000000   10668.000000   10668.000000  10668.000000  10668.000000   
mean    2017.100675   22896.685039   24827.244001    126.011436     50.770022   
std        2.167494   11714.841888   23505.257205     67.170294     12.949782   
min     1997.000000    1490.000000       1.000000      0.000000     18.900000   
25%     2016.000000   15130.750000    5968.750000    125.000000     40.900000   
50%     2017.000000   20200.000000   19000.000000    145.000000     49.600000   
75%     2019.000000   27990.000000   36464.500000    145.000000     58.900000   
max     2020.000000  145000.000000  323000.000000    580.000000    188.300000   

         engineSize  
count  10668.000000  
mean       1.930709  
std        0.602957  
min        0.000000  
25%        1.500000  
50%        2.000000  
75%        2.000000  
max        6.300000

In [11]:
X = df.iloc[:,[0,1,3,4,5,6,7,8]].values
display (X)

array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [12]:
Y = df.iloc[:,[2]].values
display (Y)


array([[12500],
       [16500],
       [11000],
       ...,
       [17199],
       [19499],
       [15999]], dtype=int64)

In [13]:
display(pd.DataFrame(X).head(5))

0     1          2      3       4    5     6    7
0   A1  2017     Manual  15735  Petrol  150  55.4  1.4
1   A6  2016  Automatic  36203  Diesel   20  64.2  2.0
2   A1  2016     Manual  29946  Petrol   30  55.4  1.4
3   A4  2017  Automatic  25952  Diesel  145  67.3  2.0
4   A3  2019     Manual   1998  Petrol  145  49.6  1.0

In [14]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,-4] = le2.fit_transform(X[:,-4])
le3 = LabelEncoder()
X[:,2] = le3.fit_transform(X[:,2])
display (X)

array([[0, 2017, 1, ..., 150, 55.4, 1.4],
       [5, 2016, 0, ..., 20, 64.2, 2.0],
       [0, 2016, 1, ..., 30, 55.4, 1.4],
       ...,
       [2, 2020, 1, ..., 150, 49.6, 1.0],
       [9, 2017, 0, ..., 150, 47.9, 1.4],
       [9, 2016, 1, ..., 150, 47.9, 1.4]], dtype=object)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
display (pd.DataFrame(X))

0         1         2         3         4         5         6  \
0     -1.123544 -0.046450 -0.108347 -0.386836  1.050783  0.357147  0.357550   
1     -0.160831 -0.507834 -1.417348  0.483989 -0.954181 -1.578323  1.037130   
2     -1.123544 -0.507834 -0.108347  0.217781  1.050783 -1.429440  0.357550   
3     -0.545916 -0.046450 -1.417348  0.047853 -0.954181  0.282706  1.276528   
4     -0.738459  0.876318 -0.108347 -0.971285  1.050783  0.282706 -0.090355   
...         ...       ...       ...       ...       ...       ...       ...   
10663 -0.738459  1.337702 -0.108347 -0.885343  1.050783  0.282706 -0.090355   
10664 -0.738459  1.337702 -0.108347 -0.972136  1.050783  0.357147 -0.090355   
10665 -0.738459  1.337702 -0.108347 -1.030381  1.050783  0.357147 -0.090355   
10666  0.609339 -0.046450 -1.417348 -0.688442  1.050783  0.357147 -0.221637   
10667  0.609339 -0.507834 -0.108347 -0.551913  1.050783  0.357147 -0.221637   

              7  
0     -0.880218  
1      0.114925  
2     -0.880218  
3      0.114925  
4     -1.543647  
...         ...  
10663 -1.543647  
10664 -1.543647  
10665 -1.543647  
10666 -0.880218  
10667 -0.880218  

[10668 rows x 8 columns]

In [16]:
from sklearn.decomposition import PCA
pca = PCA()
PCA_X = pca.fit_transform(X)
print (pd.DataFrame(PCA_X))

              0         1         2         3         4         5         6  \
0      0.348839 -1.320705  0.758203  0.465869  0.731752 -0.396933  0.456098   
1      1.865782  0.476679 -1.301954  0.981720 -0.494926  0.599873 -0.054249   
2      1.558701 -1.324328  0.699581  0.378638  0.157032  0.835341 -0.179861   
3      0.951753  0.430947 -1.242081  1.064058  0.401611 -0.713456  0.693340   
4     -0.398269 -2.180174  0.426867  0.503279  0.205285 -0.669223 -0.007795   
...         ...       ...       ...       ...       ...       ...       ...   
10663 -0.534942 -2.336535  0.249062  0.466829  0.189320 -0.659258 -0.079170   
10664 -0.602860 -2.355791  0.240742  0.470641  0.212589 -0.714629 -0.030228   
10665 -0.626151 -2.381814  0.222501  0.469296  0.211241 -0.718253 -0.010682   
10666 -0.638519 -0.705910  0.524189  1.732439 -0.690959 -0.289267  0.286513   
10667 -0.452416 -0.580826  1.127873  0.523748 -0.660974 -0.337265  0.247534   

              7  
0     -0.036303  
1     -0.205742

In [17]:
pd.DataFrame(pca.explained_variance_ratio_)

0
0  0.320625
1  0.230929
2  0.137833
3  0.122855
4  0.079896
5  0.052561
6  0.031046
7  0.024254

In [18]:
from sklearn.model_selection import train_test_split
PCA_X_train,PCA_X_test, y_train,y_test = train_test_split(PCA_X,Y,test_size=0.2,random_state=42)
print (PCA_X.shape)
print (PCA_X_train.shape)
print (PCA_X_test.shape)

(10668, 8)
(8534, 8)
(2134, 8)


In [19]:
from sklearn.decomposition import PCA
pca = PCA(n_components =2)
PCA_X = pca.fit_transform(X)
print (pd.DataFrame(PCA_X))

              0         1
0      0.348839 -1.320705
1      1.865782  0.476679
2      1.558701 -1.324328
3      0.951753  0.430947
4     -0.398269 -2.180174
...         ...       ...
10663 -0.534942 -2.336535
10664 -0.602860 -2.355791
10665 -0.626151 -2.381814
10666 -0.638519 -0.705910
10667 -0.452416 -0.580826

[10668 rows x 2 columns]


In [20]:
pd.DataFrame(pca.explained_variance_ratio_)

0
0  0.320625
1  0.230929

In [21]:
from sklearn.model_selection import train_test_split
PCA_X_train,PCA_X_test, y_train,y_test = train_test_split(PCA_X,Y,test_size=0.2,random_state=42)
print (PCA_X.shape)
print (PCA_X_train.shape)
print (PCA_X_test.shape)

(10668, 2)
(8534, 2)
(2134, 2)


In [22]:
print (pd.DataFrame(PCA_X_train))

             0         1
0    -0.202917 -0.807358
1     0.327966  2.085879
2    -2.525235  1.553503
3     2.098738  2.560943
4    -0.771594 -0.520233
...        ...       ...
8529 -2.424370  3.653725
8530  0.433779 -0.759258
8531 -0.524770 -0.439222
8532 -0.534019 -2.524312
8533 -0.725184 -1.989967

[8534 rows x 2 columns]


In [23]:
from sklearn.linear_model import LogisticRegression 
logmodel = LogisticRegression()
logmodel= logmodel.fit (PCA_X_train,y_train)

C:\Users\Sagar\.atom\recovery\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Sagar\.atom\recovery\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [24]:
y_pred = logmodel.predict(PCA_X_test)
print (y_pred)

[12000 19995 24990 ... 16000 19995 12000]


In [25]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test,y_pred)
print (cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [26]:
print (accuracy_score (y_test,y_pred))

0.007966260543580132


In [27]:
from sklearn.tree import DecisionTreeClassifier 
dt = DecisionTreeClassifier ()
dt= dt.fit (PCA_X_train,y_train)

In [28]:
y_pred = dt.predict(PCA_X_test)
print (y_pred)

[12000 19700 22995 ... 13490 19950 10000]


In [29]:
print (accuracy_score (y_test,y_pred))
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test,y_pred)
print (cm)

0.01874414245548266
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(X,Y,test_size=0.2, random_state=42)

In [31]:
pd.DataFrame(x_train)

0         1         2         3         4         5         6  \
0    -0.738459  0.876318 -0.108347 -0.804336 -0.954181  0.282706  0.048650   
1     0.609339 -1.891986  1.200654  0.996537 -0.954181  1.176000 -0.221637   
2     1.572051 -0.507834  1.200654  0.216675  1.050783  2.590382 -1.225562   
3    -0.160831 -1.891986 -1.417348  2.669305 -0.954181  0.282706  0.442498   
4     0.416796  0.876318 -0.108347 -1.052037 -0.954181  0.282706 -0.090355   
...        ...       ...       ...       ...       ...       ...       ...   
8529  0.994424 -0.046450 -1.417348  0.582270 -0.954181  2.590382 -0.893495   
8530 -0.545916 -0.046450 -0.108347  0.455909  1.050783  0.282706  0.195378   
8531 -0.545916  0.876318  1.200654 -0.635387 -0.954181  0.282706 -0.159857   
8532 -1.123544  1.337702 -0.108347 -1.032636  1.050783  0.282706 -0.221637   
8533 -1.123544  0.876318  1.200654 -0.980007  1.050783  0.282706 -0.461035   

             7  
0    -0.548504  
1     0.114925  
2     0.944211  
3     0.114925  
4    -0.548504  
...        ...  
8529  3.432068  
8530 -0.880218  
8531  0.114925  
8532 -1.543647  
8533 -0.714361  

[8534 rows x 8 columns]

In [32]:
from sklearn.linear_model import LogisticRegression 
logmodelNOPCA = LogisticRegression()
logmodelNOPCA= logmodelNOPCA.fit (x_train,y_train)

C:\Users\Sagar\.atom\recovery\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Sagar\.atom\recovery\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [33]:
y_pred = logmodelNOPCA.predict(x_test)
print (y_pred)

[11995 20000 21995 ... 14998 20000 11500]


In [34]:
cm = confusion_matrix (y_test, y_pred)
print (cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]]


In [35]:
print (accuracy_score (y_test,y_pred))

0.014526710402999063


In [36]:
from sklearn.tree import DecisionTreeClassifier 
dtnopca = DecisionTreeClassifier ()
dtnopca = dtnopca .fit (x_train,y_train)

In [37]:
y_pred = dtnopca.predict(x_test)
print (y_pred)

[10440 19700 29500 ... 14798 19950 10000]


In [38]:
print (accuracy_score (y_test,y_pred))
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test,y_pred)
print (cm)

0.02014995313964386
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [39]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA()
lda_x = lda.fit_transform(X, Y)
display (pd.DataFrame(lda_x))

C:\Users\Sagar\.atom\recovery\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0         1         2         3         4         5         6  \
0     -1.458654 -1.282898 -0.082516  1.003019 -0.168719 -0.563421  1.003474   
1     -2.010800  1.696296  0.934651 -0.429832 -1.373941 -0.520068 -0.764555   
2     -3.194185  0.784128  0.653884  0.357932 -0.977095  0.736100  1.225524   
3     -0.639768 -0.489389  0.379406  0.272125 -0.228208 -2.053523 -0.802511   
4      0.115759 -2.257485  0.425100  0.106435 -0.500579 -0.144414  0.846916   
...         ...       ...       ...       ...       ...       ...       ...   
10663  0.876588 -2.369836  1.034074 -0.346937 -0.008112 -0.308871  1.011107   
10664  0.964186 -2.459882  0.946280 -0.231519 -0.059503 -0.346856  0.968096   
10665  1.011353 -2.468517  0.914421 -0.161599 -0.124306 -0.337510  0.941074   
10666 -0.352558 -0.905210 -0.458828  0.283860 -1.469234 -1.327851  0.368259   
10667 -1.239429 -1.015337 -1.005159  0.943161 -0.948150 -0.200670  0.107492   

              7  
0      0.641124  
1      0.041654  
2     -0.183337  
3      1.278807  
4      0.132718  
...         ...  
10663  0.153594  
10664  0.193895  
10665  0.200741  
10666 -1.014243  
10667 -1.137272  

[10668 rows x 8 columns]

In [40]:
lda.explained_variance_ratio_

array([0.73105629, 0.07124033, 0.05036321, 0.0339969 , 0.03238056,
       0.02949509, 0.02744532, 0.0240223 ])

In [41]:
from sklearn.model_selection import train_test_split
lda_x_train, lda_x_test, y_train, y_test = train_test_split(lda_x ,Y, test_size = 0.2, random_state = 0)
print (lda_x.shape)
print (lda_x_train.shape)
print (lda_x_test.shape)

(10668, 8)
(8534, 8)
(2134, 8)


In [42]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(lda_x_train ,y_train)


C:\Users\Sagar\.atom\recovery\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Sagar\.atom\recovery\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [43]:
y_pred = classifier.predict (lda_x_test)
print (y_pred)

[12000 26990 31990 ... 49990 26990  9999]


In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score
print (accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

0.019681349578256794
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]]


In [45]:

from sklearn.model_selection import train_test_split
sc_x_train, sc_x_test, y_train, y_test = train_test_split(X,Y, test_size = 0.2, random_state = 0)
print (X.shape)
print (sc_x_train.shape)
print (sc_x_test.shape) 

(10668, 8)
(8534, 8)
(2134, 8)


In [78]:
classifier.fit(sc_x_train, y_train)

LogisticRegression(random_state=0)

In [79]:
y_pred = classifier.predict (sc_x_test)
print (y_pred) 

[19990 26990 31990 ... 49990 26990 11995]


In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score
print (accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)

0.019681349578256794
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]]


In [80]:
from sklearn.model_selection import cross_val_score
knn = KNeighborsClassifier(n_neighbors=4)
knn_accuracies = cross_val_score(knn,X, Y, cv=5)
print (pd.DataFrame(knn_accuracies)) 

          0
0  0.014995
1  0.020150
2  0.019681
3  0.017815
4  0.011252


In [89]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logi_accuracies = cross_val_score(logreg, X, Y, cv=5)
print (pd.DataFrame(logi_accuracies))

          0
0  0.018276
1  0.018276
2  0.013590
3  0.014534
4  0.016878


In [85]:
from sklearn.svm import SVC
svm_classifier = SVC(kernel = 'sigmoid', random_state = 0)
svm_classifier.fit(x_train, y_train) 

SVC(kernel='sigmoid', random_state=0)

In [86]:
svm_y_pred = svm_classifier.predict(x_test)
svm_y_pred

array([20000, 19990, 24990, ..., 18990, 19990, 19995], dtype=int64)

In [87]:
from sklearn.metrics import confusion_matrix
svm_cm = confusion_matrix(y_test,svm_y_pred )
svm_cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [88]:
print (accuracy_score (y_test,svm_y_pred))

0.006560449859418931


In [53]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()

In [54]:
print (accuracy_score(y_test,y_pred))

0.019681349578256794


In [55]:
X = df.iloc[:,[0,1,3,4,5,6,7,8]].values
Y = df.iloc[:,[2]].values

In [56]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,-4] = le2.fit_transform(X[:,-4])
display (X)

array([[0, 2017, 'Manual', ..., 150, 55.4, 1.4],
       [5, 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [0, 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [2, 2020, 'Manual', ..., 150, 49.6, 1.0],
       [9, 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [9, 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [57]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[2])],remainder='passthrough')
X = ct.fit_transform(X)
display (pd.DataFrame(X))

0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

In [58]:
display (pd.DataFrame(X))

0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
display (pd.DataFrame(X))


0         1         2         3         4         5         6  \
0     -0.583268  1.200728 -0.712333 -1.123544 -0.046450 -0.386836  1.050783   
1      1.714479 -0.832828 -0.712333 -0.160831 -0.507834  0.483989 -0.954181   
2     -0.583268  1.200728 -0.712333 -1.123544 -0.507834  0.217781  1.050783   
3      1.714479 -0.832828 -0.712333 -0.545916 -0.046450  0.047853 -0.954181   
4     -0.583268  1.200728 -0.712333 -0.738459  0.876318 -0.971285  1.050783   
...         ...       ...       ...       ...       ...       ...       ...   
10663 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.885343  1.050783   
10664 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.972136  1.050783   
10665 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -1.030381  1.050783   
10666  1.714479 -0.832828 -0.712333  0.609339 -0.046450 -0.688442  1.050783   
10667 -0.583268  1.200728 -0.712333  0.609339 -0.507834 -0.551913  1.050783   

              7         8         9  
0      0.357147  0.357550 -0.880218  
1     -1.578323  1.037130  0.114925  
2     -1.429440  0.357550 -0.880218  
3      0.282706  1.276528  0.114925  
4      0.282706 -0.090355 -1.543647  
...         ...       ...       ...  
10663  0.282706 -0.090355 -1.543647  
10664  0.357147 -0.090355 -1.543647  
10665  0.357147 -0.090355 -1.543647  
10666  0.357147 -0.221637 -0.880218  
10667  0.357147 -0.221637 -0.880218  

[10668 rows x 10 columns]

In [60]:
from sklearn.model_selection import train_test_split
(X_train,X_test,Y_train,Y_test) = train_test_split(X,Y,test_size=0.2,random_state=0)


In [61]:

from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state=0)
regression.fit(X_train,Y_train)


C:\Users\Sagar\AppData\Local\Temp\ipykernel_564\1570560175.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regression.fit(X_train,Y_train)


RandomForestRegressor(random_state=0)

In [62]:
y_pred = regression.predict(X_test)
display (y_pred)


array([14337.15, 23450.35, 27330.07, ..., 46275.18, 31359.  ,  9929.62])

In [63]:

print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))


[[14337.15 14998.  ]
 [23450.35 21950.  ]
 [27330.07 28990.  ]
 ...
 [46275.18 45995.  ]
 [31359.   30500.  ]
 [ 9929.62  8400.  ]]


In [64]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_pred))


R2 Score  0.9536134841307546
Mean Absolute Error 1538.730980670462


In [65]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,Y_train)


LinearRegression()

In [66]:
y_pred = reg.predict(X_test)
display (y_pred)


array([[13121.75937793],
       [29393.75937793],
       [31873.75937793],
       ...,
       [42565.75937793],
       [31485.75937793],
       [ 7377.75937793]])

In [67]:

print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))


[[13121.75937793 14998.        ]
 [29393.75937793 21950.        ]
 [31873.75937793 28990.        ]
 ...
 [42565.75937793 45995.        ]
 [31485.75937793 30500.        ]
 [ 7377.75937793  8400.        ]]


In [68]:

from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_pred))


R2 Score  0.7915565638111468
Mean Absolute Error 3379.9270826343727


In [69]:
y_pred = reg.predict(X)
display (y_pred)



array([[14681.75937793],
       [20633.75937793],
       [13881.75937793],
       ...,
       [19449.75937793],
       [20965.75937793],
       [16737.75937793]])

In [70]:
result = pd.concat([df,pd.DataFrame(y_pred)],axis=1)
display( result)


model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize             0  
0             1.4  14681.759378  
1             2.0  20633.759378  
2             1.4  13881.759378  
3             2.0  19885.759378  
4             1.0  17397.759378  
...           ...           ...  
10663         1.0  19237.759378  
10664         1.0  19321.759378  
10665         1.0  19449.759378  
10666         1.4  20965.759378  
10667         1.4  16737.759378  

[10668 rows x 10 columns]

In [71]:
from sklearn.ensemble import  ExtraTreesRegressor
ET_Model=ExtraTreesRegressor(n_estimators = 120)
ET_Model.fit(X_train,Y_train)
y_predict=ET_Model.predict(X_test)
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_predict))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_predict))


C:\Users\Sagar\AppData\Local\Temp\ipykernel_564\1396600835.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  ET_Model.fit(X_train,Y_train)


R2 Score  0.9571433653105978
Mean Absolute Error 1535.194468785796


In [72]:
y_pred = reg.predict(X)
display (y_pred)
result = pd.concat([df,pd.DataFrame(y_pred)],axis=1)
display( result)


array([[14681.75937793],
       [20633.75937793],
       [13881.75937793],
       ...,
       [19449.75937793],
       [20965.75937793],
       [16737.75937793]])

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize             0  
0             1.4  14681.759378  
1             2.0  20633.759378  
2             1.4  13881.759378  
3             2.0  19885.759378  
4             1.0  17397.759378  
...           ...           ...  
10663         1.0  19237.759378  
10664         1.0  19321.759378  
10665         1.0  19449.759378  
10666         1.4  20965.759378  
10667         1.4  16737.759378  

[10668 rows x 10 columns]

In [73]:

from sklearn.model_selection import RandomizedSearchCV

n_estimators = [int(x) for x in np.linspace(start = 80, stop = 1500, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(6, 45, num = 5)]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10]

# create random grid

rand_grid={'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

rf=RandomForestRegressor()

rCV=RandomizedSearchCV(estimator=rf,param_distributions=rand_grid,scoring='neg_mean_squared_error',n_iter=2,cv=2,random_state=42, n_jobs = 1)



In [74]:
import warnings
warnings.filterwarnings('ignore')

rCV.fit(X_train,Y_train)


RandomizedSearchCV(cv=2, estimator=RandomForestRegressor(), n_iter=2, n_jobs=1,
                   param_distributions={'max_depth': [6, 15, 25, 35, 45],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [80, 237, 395, 553, 711,
                                                         868, 1026, 1184, 1342,
                                                         1500]},
                   random_state=42, scoring='neg_mean_squared_error')

In [75]:
rf_pred=rCV.predict(X_test)
display (rf_pred)


array([14042.7222462 , 23795.16557417, 28508.59086913, ...,
       48167.3662324 , 31358.78789395, 10093.54243219])

In [76]:

from sklearn.metrics import mean_absolute_error,mean_squared_error
print('MAE',mean_absolute_error(Y_test,rf_pred))
print('MSE',mean_squared_error(Y_test,rf_pred))


MAE 1504.604942750627
MSE 5662695.938648436


In [77]:
display (r2_score(Y_test,rf_pred))

0.9587915858750957